// <auto-generated />
using CompanyRecords.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyRecords.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250627140016_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("CompanyRecords.API.Models.Entity.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Exchange = "NASDAQ",
                            Isin = "US0378331005",
                            Name = "Apple Inc.",
                            Ticker = "AAPL",
                            WebsiteUrl = "http://www.apple.com"
                        },
                        new
                        {
                            Id = 2,
                            Exchange = "Pink Sheets",
                            Isin = "US1104193065",
                            Name = "British Airways Plc",
                            Ticker = "BAIRY"
                        },
                        new
                        {
                            Id = 3,
                            Exchange = "Euronext Amsterdam",
                            Isin = "NL0000009165",
                            Name = "Heineken NV",
                            Ticker = "HEIA"
                        },
                        new
                        {
                            Id = 4,
                            Exchange = "Tokyo Stock Exchange",
                            Isin = "JP3866800000",
                            Name = "Panasonic Corp",
                            Ticker = "6752",
                            WebsiteUrl = "http://www.panasonic.co.jp"
                        },
                        new
                        {
                            Id = 5,
                            Exchange = "Deutsche Börse",
                            Isin = "DE000PAH0038",
                            Name = "Porsche Automobil",
                            Ticker = "PAH3",
                            WebsiteUrl = "https://www.porsche.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
